In [2]:
import numpy as np
## creating arrays in numpy
#1-D array

arr1 = np.array([1,2,3,5,4])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 5 4]
<class 'numpy.ndarray'>
(5,)


In [7]:
##2D arrays
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [6 7 8 9 0]]
(2, 5)


In [14]:
np.arange(0, 10, 2).reshape(5,)

array([0, 2, 4, 6, 8])

In [19]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.eye(3)##diagonal elements will be 1, rest will be zero

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
##numpy vectorised operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,9,7,0])
print("Addition", arr1 + arr2)
print("Subtraction", arr2 - arr1)

Addition [ 7  9 12 11  5]
Subtraction [ 5  5  6  3 -5]


In [23]:
## universal function
arr = np.array([2,4,5,7,9])
print(np.sqrt(arr))
print(np.sin(arr))
print(np.exp(arr))
print(np.log(arr))


[1.41421356 2.         2.23606798 2.64575131 3.        ]
[ 0.90929743 -0.7568025  -0.95892427  0.6569866   0.41211849]
[7.38905610e+00 5.45981500e+01 1.48413159e+02 1.09663316e+03
 8.10308393e+03]
[0.69314718 1.38629436 1.60943791 1.94591015 2.19722458]


In [46]:
## Array slicing and indexing
arr = np.array([[1,2,3,4,5],[6,7,9,8,0],[3,6,8,1,2]])
print("Array: \n", arr)
print(arr[0, 0])
print(arr[0][0])
print(arr[0:2,0:2])


Array: 
 [[1 2 3 4 5]
 [6 7 9 8 0]
 [3 6 8 1 2]]
1
1
[[1 2]
 [6 7]]


In [47]:
##modify array elements
arr[0,0] = 100
print(arr)

[[100   2   3   4   5]
 [  6   7   9   8   0]
 [  3   6   8   1   2]]


In [48]:
## statistical concepts
arr = ([1,2,3,4,6])
mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)
var = np. var(arr)
print(mean)
print(median)
print(std_dev)
print(var)

3.2
3.0
1.7204650534085253
2.96


In [50]:
data = np.array([1,2,3,4,5,67,8,9,10])
data > 5
data[data> 5]

array([67,  8,  9, 10])

In [ ]:
A = np.array([1,2,3,4,5])
B = np.array([2,4,6,8,10])
print(A + B)
print(B - A)
mn = np.mean(A)
print(int(mn))
print(np.sqrt(A))
print()

[ 3  6  9 12 15]
[1 2 3 4 5]
3
[1.         1.41421356 1.73205081 2.         2.23606798]


In [63]:
B = np.array([2,4,6,8,10])
print(np.sum(B))

30


In [ ]:


import numpy as np

# 3D Array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d)
print(arr_3d.shape)  # (2, 2, 2)


(2, 3)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [2]:
import random
import numpy as np
ans = np.random.randint(1, 21, size = (5, 5))
print(ans)
                


[[ 3 11  7  1 18]
 [13 19 20 17  7]
 [12  9 12 19  8]
 [10  8 12 15  8]
 [ 7 20 16 18 13]]


In [27]:
ans1 = np.arange(1, 37).reshape(6, 6)
print(ans1)
print("Sub Array")
print(ans1[2:5,1:4])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub Array
[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [ ]:
num1 = np.random.randint(5, 21, size = (3, 4))
num2 = np.random.randint(22, 43, size= (3, 4))
print(num1)
print(num2)

Addition = num1 + num2
print(Addition)
Ad = np.add(num1, num2)
print("Addition:\n",Ad)
sub = np.subtract(num1, num2)
print(sub)


[[20  5 14  5]
 [ 9  7  9 19]
 [20 19  8  7]]
[[33 42 33 26]
 [29 36 35 34]
 [30 32 25 34]]
[[53 47 47 31]
 [38 43 44 53]
 [50 51 33 41]]
Addition:
 [[53 47 47 31]
 [38 43 44 53]
 [50 51 33 41]]
[[-13 -37 -19 -21]
 [-20 -29 -26 -15]
 [-10 -13 -17 -27]]


In [38]:
np.concatenate(num1)

array([20,  5, 14,  5,  9,  7,  9, 19, 20, 19,  8,  7], dtype=int32)

In [ ]:
ar = np.arange(1,10).reshape(3, 3)
print(ar)
print(np.mean(ar))
print(np.median(ar))



[[1 2 3]
 [4 5 6]
 [7 8 9]]
5.0
5.0


In [15]:
array = np.random.randint(1, 11, size=(3, 3))
row_array = np.random.randint(1, 11, size=(3,))
print("Original array:")
print(array)
print("1D array:")
print(row_array)

# Add the 1D array to each row of the 2D array using broadcasting
result = array + row_array
print("Resulting array:")
print(result)
print("My ans")
ans = np.add(array, row_array)
print(ans)



Original array:
[[ 2 10  5]
 [ 6  4  7]
 [ 2  6  2]]
1D array:
[4 6 6]
Resulting array:
[[ 6 16 11]
 [10 10 13]
 [ 6 12  8]]
My ans
[[ 6 16 11]
 [10 10 13]
 [ 6 12  8]]


In [18]:
import numpy.ma as ma

array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
less = ma.masked_less(array, 10)

print("Original array:")
print(array)
print("Masked array:")
print(masked_array)
print("Lesser array")
print(less)

Original array:
[[12  2 19 19]
 [17 19 12  9]
 [ 2 12 16  9]
 [ 7 11 17  7]]
Masked array:
[[-- 2 -- --]
 [-- -- -- 9]
 [2 -- -- 9]
 [7 -- -- 7]]
Lesser array
[[12 -- 19 19]
 [17 19 12 --]
 [-- 12 16 --]
 [-- 11 17 --]]


In [39]:
import numpy.ma as ma

data = np.array([1, 2, -999, 4])
masked = ma.masked_equal(data, -999)
ans = ma.masked

print(masked)         # [1 2 -- 4]
print(masked.sum())   # 7 (ignores -999)


[1 2 -- 4]
7


In [ ]:
# Create a masked array of shape (3, 3) with random integers
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[18 20 16]
 [ 8  3 10]
 [18 19 15]]
Masked array:
[[-- 20 16]
 [8 -- 10]
 [18 19 --]]
Modified masked array:
[[15 20 16]
 [ 8 15 10]
 [18 19 15]]


In [15]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Use fancy indexing to extract the elements at the corners of the array
corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
a = array[0,-1]
print(a)
print("Corner elements:")
print(corners)

Original array:
[[ 8 17 13 14 12]
 [ 2 16 19 10 11]
 [10 10  2 19  8]
 [17 15  6  1 17]
 [ 5 15  5 10 20]]
12
Corner elements:
[ 8 12  5 20]


In [31]:
import numpy as np
import random 
import numpy.ma as ma
np.random.seed(5)
a = np.random.randint(1,30,size=(3,3))
b = np.random.randint(40,90, size=(3,3))
print("1st arary:\n",a)
print("2nd array:\n",b)
corners = sum[[0,0,-1,-1],[0,-1,-1,0]]
msk_arr = ma.masked_where(sum < 70, sum)
msk_filled = ma.filled(msk_arr, 0)
sum = a + b
print("sum:\n",sum)
print("corner elements:\n",corners)
print("masked array:\n",msk_arr)
print("msk filled:\n",msk_filled)

1st arary:
 [[ 4 15 16]
 [ 7 23 17]
 [10  9  5]]
2nd array:
 [[79 67 88]
 [70 56 47]
 [52 55 89]]
sum:
 [[ 83  82 104]
 [ 77  79  64]
 [ 62  64  94]]
corner elements:
 [ 83 104  94  62]
masked array:
 [[83 82 104]
 [77 79 --]
 [-- -- 94]]
msk filled:
 [[ 83  82 104]
 [ 77  79   0]
 [  0   0  94]]
